# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: du2x Blog
email: dudumonteiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Data science, python and other IT cool stuff. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://du2x.github.io" # the base hostname & protocol for your site
twitter_username: du2x
github_username:  du2x

# Build settings
#markdown: kramdown

markdown: redcarpet
redcarpet:
   extensions: ["tables", "fenced_code_blocks"]

